### ISSUE TITLE
... 🕺 AntiAim 🕺 - Absinthe - Rage-SemiRage-helper.lua error

### ISSUE THREAD

**Issue by MictianTheGod** [ticzz/Aimware-v5-luas#2]
after a long time i came back to aimware and i don't remember the lua api if you tell me what to do with it specifically and how to fix it :)
... 🕺 AntiAim 🕺 - Absinthe - Rage-SemiRage-helper.lua:484: '=' expected near ''

**Comment by ticzz** [comment]
> after a long time i came back to aimware and i don't remember the lua api if you tell me what to do with it specifically and how to fix it :) ... AntiAim - Absinthe - Rage-SemiRage-helper.lua:484: '=' expected near ''

Fixed the error.. just need to redownload it
