### ISSUE TITLE
LICENSE issues

### ISSUE THREAD

**Issue by Ourmine-Onyx** [ticzz/Aimware-v5-luas#3]
Delete all my LUA's
_I join the others you have a week to delete my code._

Delete this files from your repository:
- [[Onyx] Lobby Functions](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20Lobby%20Functions.lua)

- [[Onyx] Mass Invite](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20Mass%20Invite.lua)

- [[Onyx] ProfileChanger](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20ProfileChanger.lua)

- [[Onyx] Troll Menu and Blockbot](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20Troll%20Menu%20and%20Blockbot.lua)

- [[Onyx] Invite Everyone](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20Invite%20Everyone.lua)

- [[Onyx] Chat HitLog](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20Chat%20HitLog.lua)

- [[Onyx] FakePrime](https://github.com/ticzz/Aimware-v5-luas/blob/master/%5BOnyx%5D%20FakePrime.lua)

**Comment by ticzz** [comment]
deleted files.. fuck u crying kid
