### ISSUE TITLE
brain issue

### ISSUE THREAD

**Issue by ieathumanslol** [ticzz/Aimware-v5-luas#4]
Delete all my LUAs

Delete these files from your repository:
     ProjectDumpMania and  
     Antiaim-ProjectDumpMania

**Comment by Le0Developer** [comment]
> Delete all my LUAs

This also affects but was forgotten to mention: 
 - [ANTIaim - PDM config.lua](https://github.com/ticzz/Aimware-v5-luas/blob/master/ANTIaim%20-%20PDM%20config.lua)

**Comment by ieathumanslol** [comment]
> > Delete all my LUAs
> 
> This also affects but was forgotten to mention: 
>  - [ANTIaim - PDM config.lua](https://github.com/ticzz/Aimware-v5-luas/blob/master/ANTIaim%20-%20PDM%20config.lua)

and that one

**Comment by ticzz** [comment]
done, sry for trouble..

i really don´t know why its three times in here..
