### ISSUE TITLE
LICENSE issues

### ISSUE THREAD

**Issue by atk3001** [ticzz/Aimware-v5-luas#5]
Just wanna tell you that you reupload my luas without copyright mention which violates the [License](https://github.com/atk3001/Aimware-scripts/blob/master/LICENSE) of my work.
Kindly remove my luas from this repo within the next week or so or I'll let github take them down.

Affected files:
[ViewModelchanger incl Scopefix](https://github.com/ticzz/Aimware-v5-luas/blob/master/ViewModelchanger%20incl%20Scopefix.lua)
[RevolverFix](https://github.com/ticzz/Aimware-v5-luas/blob/master/RevolverFix.lua)
[Clantag](https://github.com/ticzz/Aimware-v5-luas/blob/master/Clantag.lua)
[Clantag SlidingAnimated](https://github.com/ticzz/Aimware-v5-luas/blob/master/Clantag%20SlidingAnimated.lua)

**Comment by ticzz** [comment]
done
