### ISSUE TITLE
Desc? 

### ISSUE THREAD

**Issue by vollh4rD** [ticzz/Aimware-v5-luas#6]
could you explain what is this lua doing ?

**Comment by ticzz** [comment]
Which lua do u mean? The repository "Aimware-v5-luas" contains ~ 400 lua-scripts..!

**Comment by vollh4rD** [comment]
Auto Report Players Tool.lua

**Comment by ticzz** [comment]
It will automaticlly report the players on specific conditions..
 u can set who will be reported and when it will report (for example if he killed u or after round ends)
when one condition is met the script automaticlly report the specific players, it was made for matchmaking-hvh with spinbots, so if the other guy could kill you he definitely was cheater too so script reported him automaticly..
omg bad explantation but i think /hope u get what i tried to tell!= ;DDD

**Comment by ticzz** [comment]
this is the menu!

![Anmerkung 2022-04-30 162458](https://user-images.githubusercontent.com/32612882/166109550-55b2102b-69e0-4805-89bf-17f015d415f7.png)

**Comment by vollh4rD** [comment]
yea I got it. Is there any way to report after every 5 seconds or something like that ?

**Comment by vollh4rD** [comment]
![image](https://user-images.githubusercontent.com/59693437/166423888-cc5f717e-727c-4b7a-b12a-1b29830649cd.png)
why does it show only one panel ?

**Comment by Teemoplays** [comment]
> could you explain what is this lua doing ? 
> 

Try looking at the code you might understand what it's doing
